In [37]:
from pathlib import Path
import typing as T
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import numpy
import xarray as xr
import iris
import iris.plot
import numpy as np
import os
import sys
import textwrap
import itertools
import ants
import warnings

In [38]:
PATH = Path('/home/548/pag548/cylc-run/u-dq126/share/cycle/20220227T0000Z/Flagship_ERA5to1km/5km/RAL3P2/um')

In [39]:
files = PATH.glob('*.nc')

In [40]:
for file in files:
    print (file)

/home/548/pag548/cylc-run/u-dq126/share/cycle/20220227T0000Z/Flagship_ERA5to1km/5km/RAL3P2/um/umnsaa_pverd012.nc
/home/548/pag548/cylc-run/u-dq126/share/cycle/20220227T0000Z/Flagship_ERA5to1km/5km/RAL3P2/um/umnsaa_pvera012.nc
/home/548/pag548/cylc-run/u-dq126/share/cycle/20220227T0000Z/Flagship_ERA5to1km/5km/RAL3P2/um/umnsaa_pverc012.nc
/home/548/pag548/cylc-run/u-dq126/share/cycle/20220227T0000Z/Flagship_ERA5to1km/5km/RAL3P2/um/umnsaa_pb000.nc
/home/548/pag548/cylc-run/u-dq126/share/cycle/20220227T0000Z/Flagship_ERA5to1km/5km/RAL3P2/um/umnsaa_pb012.nc
/home/548/pag548/cylc-run/u-dq126/share/cycle/20220227T0000Z/Flagship_ERA5to1km/5km/RAL3P2/um/umnsaa_pverb012.nc
/home/548/pag548/cylc-run/u-dq126/share/cycle/20220227T0000Z/Flagship_ERA5to1km/5km/RAL3P2/um/umnsaa_pverc000.nc
/home/548/pag548/cylc-run/u-dq126/share/cycle/20220227T0000Z/Flagship_ERA5to1km/5km/RAL3P2/um/umnsaa_pvera000.nc
/home/548/pag548/cylc-run/u-dq126/share/cycle/20220227T0000Z/Flagship_ERA5to1km/5km/RAL3P2/um/umnsaa_p

In [91]:
files = PATH.glob('*.nc')
output = {}
long_names = []
var_names = []
for file in files:
    cubes = iris.load(file)
    for cube in cubes:
        #print (f'{file.name} {cube.long_name} {cube.standard_name} {cube.var_name}')
        long_names.append(cube.long_name)
        var_names.append(cube.var_name)
        output[cube.var_name] = { 'long name' : cube.long_name, 'file' : file.name}

In [92]:
unique_long_names = (list(set(long_names)))
print (unique_long_names)

['TOTAL COLUMN DRY MASS  RHO GRID', 'LARGE SCALE RAINFALL RATE    KG/M2/S', 'TURBULENT MIXING HT AFTER B.LAYER m', 'U WIND ON PRESSURE LEVELS    B GRID', 'LARGE SCALE SNOWFALL RATE    KG/M2/S', 'TOTAL DOWNWARD SURFACE SW FLUX', 'CLOUD FRACTION BELOW 1000 FT ASL', 'OUTGOING SW RAD FLUX (TOA)', 'SNOW AMOUNT OVER LAND AFT TSTP KG/M2', 'CLOUD BASE ASL COVER.GT.2.5 OCTA KFT', 'CEILOMETER CLD AMT MAX/RANDOM OVERLP', 'NET DOWN SURFACE SW FLUX : CORRECTED', 'TOTAL COLUMN Q (WATER VAPOUR PATH)', 'LOW CLOUD AMOUNT', 'CUMULUS-CAPPED BL INDICATOR', 'WIND GUST  (M/S)', 'DOWNWARD LW RAD FLUX: SURFACE', 'WET BULB POTENTIAL TEMPERATURE     K', 'TOTAL COLUMN WET MASS  RHO GRID', 'PRESSURE AT MEAN SEA LEVEL', 'LARGE SCALE SNOW AMOUNT     KG/M2/TS', 'VIS AT 1.5M  (incl precip)         M', 'DEEP SOIL TEMP. AFTER HYDROLOGY DEGK', 'RADAR REFLECTIVITY AT 1KM AGL (dBZ)', 'NUMBER OF LIGHTNING FLASHES', 'SURFACE LATENT HEAT FLUX        W/M2', '10 METRE WIND V-COMP         B GRID', 'GEOPOTENTIAL HEIGHT ON P LEV/

In [43]:
len(unique_long_names)

58

In [44]:
unique_var_names = (list(set(var_names)))
print (unique_var_names)

['STASH_m01s01i205', 'STASH_m01s00i409', 'STASH_m01s09i218_2', 'STASH_m01s03i245', 'STASH_m01s03i253', 'STASH_m01s01i205_2', 'STASH_m01s16i204', 'STASH_m01s04i203_2', 'STASH_m01s00i025', 'STASH_m01s04i202', 'STASH_m01s30i404', 'STASH_m01s16i202', 'STASH_m01s09i202_2', 'STASH_m01s03i226_2', 'STASH_m01s03i250', 'STASH_m01s30i403_2', 'STASH_m01s00i033', 'STASH_m01s09i210', 'STASH_m01s08i225_2', 'STASH_m01s15i201_2', 'STASH_m01s01i202_2', 'STASH_m01s04i201', 'STASH_m01s04i204_2', 'STASH_m01s15i202', 'STASH_m01s01i202', 'STASH_m01s03i281_2', 'STASH_m01s16i205_2', 'STASH_m01s02i207', 'STASH_m01s03i234', 'STASH_m01s03i304_2', 'STASH_m01s03i281', 'STASH_m01s00i023', 'STASH_m01s09i202_3', 'STASH_m01s08i223', 'STASH_m01s16i205', 'STASH_m01s01i235', 'STASH_m01s03i236_2', 'STASH_m01s03i248', 'STASH_m01s02i207_2', 'STASH_m01s30i405', 'STASH_m01s03i248_2', 'STASH_m01s16i204_2', 'STASH_m01s16i222', 'STASH_m01s09i204_3', 'STASH_m01s04i202_2', 'STASH_m01s03i236', 'STASH_m01s03i225_2', 'STASH_m01s08i223

In [45]:
len(unique_var_names)

107

In [46]:
# Compare to STASHC file
STASHC_file='/home/548/pag548/cylc-run/u-dq126/work/20220227T0000Z/Flagship_ERA5to1km_5km_RAL3P2_um_fcst_000/STASHC'

In [47]:
with open(STASHC_file, "r") as file:
    stash = file.read()

In [48]:
stash.count('&umstash_streq')

130

In [55]:
stash.count('item=')

130

In [49]:
# Ok let's look at the levels of various files.
# TEMPERATURE ON P LEV/P GRID air_temperature STASH_m01s16i203_2

In [50]:
stash[:500]

"&umstash_streq\ndom_name='DIAG',\nisec=4,\nitem=201,\npackage='',\ntim_name='t1min',\nuse_name='USR_DIAGS',\n/\n&umstash_streq\ndom_name='DIAG',\nisec=5,\nitem=201,\npackage='',\ntim_name='tsmin',\nuse_name='USR_DIAGS',\n/\n&umstash_streq\ndom_name='DIAG',\nisec=16,\nitem=222,\npackage='',\ntim_name='t1min',\nuse_name='USR_DIAGS',\n/\n&umstash_streq\ndom_name='DIAG',\nisec=4,\nitem=201,\npackage='',\ntim_name='tsmin',\nuse_name='USR_DIAGS',\n/\n&umstash_streq\ndom_name='DIAG',\nisec=16,\nitem=222,\npackage='',\ntim_name='tsmin',\nus"

In [96]:
cubes = iris.load(PATH / 'umnsaa_pverd000.nc')

In [97]:
cubes

[<iris 'Cube' of air_temperature / (K) (time: 1; air_pressure: 16; grid_latitude: 976; grid_longitude: 1466)>,
<iris 'Cube' of air_temperature / (K) (time: 4; air_pressure: 16; grid_latitude: 976; grid_longitude: 1466)>,
<iris 'Cube' of geopotential_height / (m) (time: 4; air_pressure: 16; grid_latitude: 976; grid_longitude: 1466)>,
<iris 'Cube' of geopotential_height / (m) (time: 1; air_pressure: 16; grid_latitude: 976; grid_longitude: 1466)>,
<iris 'Cube' of relative_humidity / (%) (time: 4; air_pressure: 16; grid_latitude: 976; grid_longitude: 1466)>,
<iris 'Cube' of relative_humidity / (%) (time: 1; air_pressure: 16; grid_latitude: 976; grid_longitude: 1466)>]

In [98]:
temp = cubes[0]
temp

<iris 'Cube' of air_temperature / (K) (time: 1; air_pressure: 16; grid_latitude: 976; grid_longitude: 1466)>

In [99]:
temp.coord('air_pressure').points

array([1000.,  950.,  925.,  850.,  800.,  750.,  700.,  650.,  600.,
        500.,  400.,  300.,  250.,  200.,  150.,  100.])

In [102]:
temp.coord('time').points

array([0.])

In [103]:
temp.coord('time').units

Unit('days since 2022-02-27 00:00:00', calendar='standard')

In [100]:
temp.attributes['STASH']

STASH(model=1, section=16, item=203)

There are only two entries in STASHC with this configuration

In [101]:
for st in unique_var_names:
    if 'STASH_m01s16i203' in st:
        print (st,output[st])

STASH_m01s16i203_2 {'long name': 'TEMPERATURE ON P LEV/P GRID', 'file': 'umnsaa_pverd000.nc'}
STASH_m01s16i203 {'long name': 'TEMPERATURE ON P LEV/P GRID', 'file': 'umnsaa_pverd000.nc'}


In [105]:
# Read the second temperature cube
temp_2=cubes[1]
temp_2.coord('time').points

array([ 3.,  6.,  9., 12.])

In [108]:
temp_2.coord('time').units

Unit('hours since 2022-02-27 00:00:00', calendar='standard')